# Generated by Django 5.0.6 on 2024-06-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='rating',
        ),
    ]
